--· EN_US/Faith.sql
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BELIEF_ANCESTOR_WORSHIP', '+2 [ICON_CULTURE] Culture from Shrines', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BELIEF_CATHEDRALS', 'Use [ICON_PEACE] Faith to purchase Cathedrals (1 [ICON_GREAT_WORK] Great Work of Art slot, 1 [ICON_PEACE] Faith, +1 [ICON_HAPPINESS_1] City Happiness)', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BELIEF_CEREMONIAL_BURIAL', '+1 [ICON_HAPPINESS_1] National Happiness for each city following this religion', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BELIEF_CHORAL_MUSIC', '+6 [ICON_CULTURE] Culture from Temples in cities with 5+ followers', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BELIEF_CHURCH_PROPERTY', '+3 [ICON_GOLD] Gold for each city following this religion', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BELIEF_GOD_OF_ABUNDANCE', '+2 [ICON_PRODUCTION] Production from open Tundra', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BELIEF_DANCE_AURORA', '+2 [ICON_PEACE] Faith from open Tundra', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-07-11'), 'TXT_KEY_BELIEF_TRANQUIL_REFUGE_SHORT', 'Tranquil Refuge', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-07-11'), 'TXT_KEY_BELIEF_TRANQUIL_REFUGE', '+2 [ICON_FOOD][ICON_CULTURE] Food and Culture from Oasis', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BELIEF_DEFENDER_FAITH', '+40% [ICON_STRENGTH] Combat Strength near friendly cities that follow this religion', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BELIEF_DIVINE_INSPIRATION', '+2 [ICON_TOURISM][ICON_PEACE] Tourism and Faith from each World Wonder', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-21'), 'TXT_KEY_BELIEF_FERTILITY_RITES', '+25% [ICON_FOOD] Surplus Food in cities', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-21'), 'TXT_KEY_BELIEF_FEED_WORLD', '+3 [ICON_FOOD] Food from Shrines and Temples', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-23'), 'TXT_KEY_BELIEF_FORMAL_LITURGY', '+1 [ICON_CULTURE][ICON_PEACE] Culture and Faith for each Gold and Silver', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BELIEF_GOD_CRAFTSMEN', '+3 [ICON_PRODUCTION] Production in cities with 3+ [ICON_CITIZEN] population', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-23'), 'TXT_KEY_BELIEF_GOD_FESTIVALS', '+1 [ICON_CULTURE][ICON_PEACE] Culture and Faith from Wine and Incense', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-21'), 'TXT_KEY_BELIEF_GOD_SEA', '+2 [ICON_PRODUCTION] Production from Fishing Boats', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-21'), 'TXT_KEY_BELIEF_GOD_TRANQUILITY_SHORT', 'God of Tranquility', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-21'), 'TXT_KEY_BELIEF_GOD_TRANQUILITY', '+2 [ICON_PEACE] Faith from Fishing Boats', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BELIEF_GOD_WAR', 'Gain 2 [ICON_PEACE] Faith per 1 [ICON_STRENGTH] Strength of defeated units', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-21'), 'TXT_KEY_BELIEF_GODDESS_HUNT', '+2 [ICON_FOOD] Food from Camps', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BELIEF_GURUSHIP', '+4 [ICON_RESEARCH] Science in cities with a Specialist', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BELIEF_HOLY_ORDER', '75% [ICON_PEACE] Cost for missionaries and inquisitors', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BELIEF_INITIATION_RITES', '+200 [ICON_GOLD] Gold the first time this religion spreads to each city', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BELIEF_INTERFAITH_DIALOGUE', '+50 [ICON_RESEARCH] Science per follower of other faiths when this religion spreads to cities', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BELIEF_JUST_WAR', '+40% [ICON_STRENGTH] Combat Strength near cities that follow this religion', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-02-06'), 'TXT_KEY_BELIEF_LITURGICAL_DRAMA', '+4 [ICON_PEACE] Faith from Theaters in cities with 3+ followers', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BELIEF_MESSENGER_GODS', '+3 [ICON_RESEARCH] Science in cities with a [ICON_CONNECTED] Trade Route', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BELIEF_MESSIAH', '125% strength and 75% [ICON_PEACE] Cost for Great Prophets', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BELIEF_MISSIONARY_ZEAL', '150% Conversion Strength for missionaries', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BELIEF_MONASTERIES', 'Use [ICON_PEACE] Faith to purchase Monasteries (+50% [ICON_PEACE] Faith, +2 [ICON_CULTURE] Culture)', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-21'), 'TXT_KEY_BELIEF_MONUMENT_GODS', '+25% [ICON_PRODUCTION] Production of Ancient/Classical Wonders', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BELIEF_MOSQUES', 'Use [ICON_PEACE] Faith to purchase Mosques (4 [ICON_PEACE] Faith, +2 [ICON_CULTURE] Culture, +1 [ICON_HAPPINESS_1] City Happiness)', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BELIEF_ONE_WITH_NATURE', '+2 [ICON_FOOD][ICON_PRODUCTION][ICON_GOLD][ICON_RESEARCH][ICON_CULTURE][ICON_PEACE] every yield from Natural Wonders', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BELIEF_OPEN_SKY', '+2 [ICON_CULTURE] Culture from Pastures', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BELIEF_ORAL_TRADITION', '+2 [ICON_CULTURE] Culture from Plantations', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BELIEF_PAGODAS', 'Use [ICON_PEACE] Faith to purchase Pagodas (+2 [ICON_HAPPINESS_1] City Happiness, +1 [ICON_PEACE] Faith, +1 [ICON_CULTURE] Culture)', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BELIEF_PAPAL_PRIMACY', '+30 [ICON_INFLUENCE] resting influence with City-States following this religion', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BELIEF_PEACE_LOVING', '+1 [ICON_HAPPINESS_1] National Happiness for every 3 followers in peaceful foreign cities', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BELIEF_PILGRIMAGE', '+5 [ICON_CULTURE] Culture from each foreign city following this religion', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BELIEF_RELIGIOUS_ART', '+10 [ICON_TOURISM][ICON_CULTURE] Tourism and Culture from Hermitage', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BELIEF_RELIGIOUS_COMMUNITY', '+1% [ICON_PRODUCTION] Production for each follower (max +20%)', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BELIEF_RELIGIOUS_SETTLEMENTS', '+1 [ICON_PEACE] Faith from Villages', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BELIEF_RELIGIOUS_UNITY', '500% religion spread speed to friendly city-states', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BELIEF_RELIQUARY', 'Gain 500 [ICON_PEACE] Faith each time a Great Person is expended', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BELIEF_SACRED_ISLES_SHORT', 'Sacred Isles', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BELIEF_SACRED_ISLES', '+2 [ICON_CULTURE][ICON_PEACE] Culture and Faith from Isles', '', '');
--INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BELIEF_SACRED_PATH', '+1 [ICON_FOOD] Food from Jungle tiles', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BELIEF_SWORD_PLOWSHARES', '+25% [ICON_FOOD] Surplus Food in all cities when not at war', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BELIEF_TITHE', '+1 [ICON_GOLD] Gold for every 5 followers of this religion', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_BELIEF_WORLD_CHURCH', '+1 [ICON_CULTURE] Culture for every 3 followers of this religion in foreign civilizations', '', '');


UPDATE LoadedFile SET Value=1 WHERE Type='Faith.sql';
