--? EN_US/Flavors.sql
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-26'), 'TXT_KEY_GOOD_FOR_RANKS', 'Good For Ranks', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-26'), 'TXT_KEY_GOOD_FOR_RANK_1', '[COLOR_PLAYER_ORANGE_TEXT]High[ENDCOLOR]', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-26'), 'TXT_KEY_GOOD_FOR_RANK_2', '[COLOR:255:60:255:255]Wondrous[ENDCOLOR]', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-26'), 'TXT_KEY_GOOD_FOR_RANK_3', '[COLOR_RESEARCH_STORED]Unique[ENDCOLOR]', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-26'), 'TXT_KEY_GOOD_FOR_RANK_4', '[COLOR_PLAYER_LIGHT_GREEN]Good[ENDCOLOR]', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-26'), 'TXT_KEY_GOOD_FOR_RANK_5', 'Average', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-26'), 'TXT_KEY_GOOD_FOR_RANK_6', '[COLOR_GREY]Low[ENDCOLOR]', '', '');
/* Flavors */
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-26'), 'TXT_KEY_FLAVOR_OFFENSE', 'Offense', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-26'), 'TXT_KEY_FLAVOR_DEFENSE', 'Defense', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-26'), 'TXT_KEY_FLAVOR_SOLDIER', 'Soldier', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-26'), 'TXT_KEY_FLAVOR_MOBILE', 'Mobile', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-26'), 'TXT_KEY_FLAVOR_ANTI_MOBILE', 'Anti-Mobile', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-26'), 'TXT_KEY_FLAVOR_RECON', 'Detection', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-26'), 'TXT_KEY_FLAVOR_HEALING', 'Healing', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-26'), 'TXT_KEY_FLAVOR_PILLAGE', 'Pillage', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-26'), 'TXT_KEY_FLAVOR_VANGUARD', 'Vanguard', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-26'), 'TXT_KEY_FLAVOR_RANGED', 'Ranged', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-26'), 'TXT_KEY_FLAVOR_SIEGE', 'Siege', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-26'), 'TXT_KEY_FLAVOR_NAVAL', 'Anti-Ship', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-26'), 'TXT_KEY_FLAVOR_NAVAL_BOMBARDMENT', 'Naval Bombardment', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-26'), 'TXT_KEY_FLAVOR_NAVAL_GROWTH', 'Port Infrastructure', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-26'), 'TXT_KEY_FLAVOR_NAVAL_RECON', 'Sea Exploration', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-26'), 'TXT_KEY_FLAVOR_NAVAL_TILE_IMPROVEMENT', 'Sea Tile Improvement', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-26'), 'TXT_KEY_FLAVOR_AIR', 'Air', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-26'), 'TXT_KEY_FLAVOR_AIR_CARRIER', 'Aircraft Carrier', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-26'), 'TXT_KEY_FLAVOR_ANTIAIR', 'Anti-Air', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-26'), 'TXT_KEY_FLAVOR_NUKE', 'Nuke', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-26'), 'TXT_KEY_FLAVOR_EXPANSION', 'Expansion', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-26'), 'TXT_KEY_FLAVOR_HAPPINESS', 'Happiness', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-26'), 'TXT_KEY_FLAVOR_PRODUCTION', 'Production', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-26'), 'TXT_KEY_FLAVOR_GOLD', 'Gold', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-26'), 'TXT_KEY_FLAVOR_GROWTH', 'Growth', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-26'), 'TXT_KEY_FLAVOR_SCIENCE', 'Science', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-26'), 'TXT_KEY_FLAVOR_CULTURE', 'Culture', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-26'), 'TXT_KEY_FLAVOR_GREAT_PEOPLE', 'Great People', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-26'), 'TXT_KEY_FLAVOR_CITY_DEFENSE', 'City Defense', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-26'), 'TXT_KEY_FLAVOR_TILE_IMPROVEMENT', 'Tile Improvement', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-26'), 'TXT_KEY_FLAVOR_INFRASTRUCTURE', 'Infrastructure', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-26'), 'TXT_KEY_FLAVOR_WATER_CONNECTION', 'Water Connection', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-26'), 'TXT_KEY_FLAVOR_WONDER', 'Wonder', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-26'), 'TXT_KEY_FLAVOR_DIPLOMACY', 'Diplomacy', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-26'), 'TXT_KEY_FLAVOR_SPACESHIP', 'Spaceship', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-26'), 'TXT_KEY_FLAVOR_ESPIONAGE', 'Espionage', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-26'), 'TXT_KEY_FLAVOR_RELIGION', 'Religion', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-26'), 'TXT_KEY_FLAVOR_TOURISM', 'Tourism', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-26'), 'TXT_KEY_FLAVOR_I_LAND_TRADE_ROUTE', 'Land Trade', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-26'), 'TXT_KEY_FLAVOR_I_SEA_TRADE_ROUTE', 'Sea Trade', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-26'), 'TXT_KEY_FLAVOR_I_TRADE_DESTINATION', 'Trade Destination', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-26'), 'TXT_KEY_FLAVOR_I_TRADE_ORIGIN', 'Trade Origin', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-26'), 'TXT_KEY_FLAVOR_ARCHAEOLOGY', 'Archaeology', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-26'), 'TXT_KEY_FLAVOR_AIRLIFT', 'Airlift', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-26'), 'TXT_KEY_FLAVOR_RES_STRATEGIC', 'Strategic Resources', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-26'), 'TXT_KEY_FLAVOR_RES_LUXURY', 'Luxury Resources', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-26'), 'TXT_KEY_FLAVOR_RES_SEA', 'Sea Resources', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-26'), 'TXT_KEY_FLAVOR_RES_GRAINS', 'Grain Resources', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-26'), 'TXT_KEY_FLAVOR_RES_RELIGIOUS', 'Religious Resources', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-26'), 'TXT_KEY_FLAVOR_RES_EXOTIC', 'Exotic Food Resources', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-26'), 'TXT_KEY_FLAVOR_RES_COSTUME', 'Costume Resources', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-26'), 'TXT_KEY_FLAVOR_RES_ORE', 'Ore Resources', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-08-26'), 'TXT_KEY_FLAVOR_RES_CURRENCY', 'Currency Resources', '', '');


UPDATE LoadedFile SET Value=1 WHERE Type='Cat_Flavors.sql';
