--? EN_US/TW_PromotionStats.sql
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_ATTACK', 'Attack', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_DEFENSE', 'Defense', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_VS', 'vs', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_SIGHT_RANGE', 'Sight Range', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_RANGE', 'Range', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_MOVES', 'Moves', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_EXPERIENCE', 'Experience', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_RANGED_ATTACKS', 'Ranged Attacks', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_AIR_SWEEPS', 'Air Sweeps', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_FASTER_IN', 'Faster in', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_ROUGH_TERRAIN', '[COLOR_POSITIVE_TEXT]ROUGH[ENDCOLOR] Terrain (Hills, Forest or Jungle)', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_OPEN_TERRAIN', '[COLOR_POSITIVE_TEXT]OPEN[ENDCOLOR] Terrain (NO Hills, Forest or Jungle)', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_WOUNDED_UNITS', 'Wounded Units', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_FRIENDLY', 'Friendly', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_NEUTRAL', 'Neutral', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_ENEMY', 'Enemy', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_IN_TERRITORY', 'in {1_num} Territory', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_UPGRADE_COST', 'Upgrade Cost', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_STRENGTH', 'Strength', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_CANNOT ENTER', 'Cannot enter', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_UNTIL', 'until', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_HEALING', 'Healing', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_FORTIFIED_UNITS', 'Fortified Units', '', '');
/* Special Abilities */
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_PROMOTION_EFFECT_ADJACENT_ENEMIES', 'for [COLOR_POSITIVE_TEXT]adjacent enemy units[ENDCOLOR]', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_PROMOTION_EFFECT_ADJACENT_FRIENDLY', 'for units in adjacent tiles', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_PROMOTION_EFFECT_AIR_SWEEP', 'Can Air Sweep to clear intercepting Units.', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_PROMOTION_EFFECT_AMPHIBIOUS', 'Full damage when attacking from sea or across rivers.', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_PROMOTION_EFFECT_BLITZ', 'Can [COLOR_POSITIVE_TEXT]attack twice[ENDCOLOR]', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_PROMOTION_EFFECT_CAN_HEAL', 'Can heal', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_PROMOTION_EFFECT_CAPITAL_BONUS', 'in the [COLOR_POSITIVE_TEXT]Capital[ENDCOLOR]; bonus falls off as the unit gets further away', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_PROMOTION_EFFECT_CAPTURE_SHIPS', '[COLOR_POSITIVE_TEXT]Captures[ENDCOLOR] defeated enemy [COLOR_POSITIVE_TEXT]Ships[ENDCOLOR]', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_PROMOTION_EFFECT_CARGO', 'Can Carry [COLOR_POSITIVE_TEXT]{1_num}[ENDCOLOR] Cargo', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_PROMOTION_EFFECT_EMBARKATION', 'Can embark onto [COLOR_POSITIVE_TEXT]Water Tiles[ENDCOLOR]', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_PROMOTION_EFFECT_EVADE', 'chance to [COLOR_POSITIVE_TEXT]Evade[ENDCOLOR] interception', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_PROMOTION_EFFECT_EXTRA_INTERCEPTION', '+1 extra [COLOR_POSITIVE_TEXT]Interception[ENDCOLOR] may be made per turn', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_PROMOTION_EFFECT_FAST_ATTACK', 'Attacks use [COLOR_POSITIVE_TEXT]1 Move[ENDCOLOR]', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_PROMOTION_EFFECT_FLAT_MOVEMENT', 'All movement uses [COLOR_PLAYER_ORANGE_TEXT]1 Move[ENDCOLOR]', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_PROMOTION_EFFECT_FREE_UPGRADES', 'Free upgrades', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_PROMOTION_EFFECT_GREAT_ADMIRAL', 'Improves combat effectiveness of nearby [COLOR_POSITIVE_TEXT]Ships[ENDCOLOR]', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_PROMOTION_EFFECT_GREAT_GENERAL', 'Improves combat effectiveness of nearby [COLOR_POSITIVE_TEXT]Land Units[ENDCOLOR]', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_PROMOTION_EFFECT_GREAT_GENERAL_MOVEMENT', '[COLOR_POSITIVE_TEXT]Great Generals[ENDCOLOR] move at rate of this unit if they start the turn [COLOR_POSITIVE_TEXT]stacked[ENDCOLOR]', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_PROMOTION_EFFECT_GREAT_GENERAL_RATE', 'Great General creation rate', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_PROMOTION_EFFECT_HEAL_ON_KILL', '[COLOR_POSITIVE_TEXT]Heal {1_num} health[ENDCOLOR] from killing Non-Barbarian units', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_PROMOTION_EFFECT_IGNORE_TERRAIN_COST', 'Ignores Terrain Costs', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_PROMOTION_EFFECT_INDIRECT_FIRE', 'Can attack [COLOR_POSITIVE_TEXT]over obstacles[ENDCOLOR]', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_PROMOTION_EFFECT_INSTANT_HEAL', '[COLOR_POSITIVE_TEXT]Heal {1_num} health[ENDCOLOR][NEWLINE][COLOR_NEGATIVE_TEXT]Ends[ENDCOLOR] this opportunity to choose a promotion', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_PROMOTION_EFFECT_INTERCEPTION', 'chance to [COLOR_POSITIVE_TEXT]Intercept[ENDCOLOR] aircraft', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_PROMOTION_EFFECT_MARCH', 'Attacking and moving do not prevent healing', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_PROMOTION_EFFECT_MOUNTAIN_PASS', 'Can pass over [COLOR_POSITIVE_TEXT]Mountains[ENDCOLOR], but takes damage if [COLOR_NEGATIVE_TEXT]ending its turn[ENDCOLOR] on a Mountain', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_PROMOTION_EFFECT_MOVE_IMPASSIBLE', 'Can move through [COLOR_POSITIVE_TEXT]Ice and Mountains[ENDCOLOR]', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_PROMOTION_EFFECT_MUST_SET_UP', 'Must set up to ranged attack', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_PROMOTION_EFFECT_NO_CITY_CAPTURE', 'Unable to Capture Cities', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_PROMOTION_EFFECT_NO_DEFENSE_BONUS', 'No Defensive Terrain Bonuses', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_PROMOTION_EFFECT_NO_MELEE_ATTACK', 'Cannot melee attack', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_PROMOTION_EFFECT_NO_UNIT_ATTACK', 'Cannot attack [COLOR_NEGATIVE_TEXT]units[ENDCOLOR]', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_PROMOTION_EFFECT_PARADROP', 'Can [COLOR_POSITIVE_TEXT]Paradrop[ENDCOLOR]', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_PROMOTION_EFFECT_RIVAL_TERRITORY', 'Can enter [COLOR_POSITIVE_TEXT]Rival Territory[ENDCOLOR]', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_PROMOTION_EFFECT_RIVAL_TERRITORY_FAITH', '{PROMOTION_UNWELCOME_EVANGELIST_HELP}', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_PROMOTION_EFFECT_STRONGER_INTERCEPTION', 'stronger [COLOR_POSITIVE_TEXT]Interceptions[ENDCOLOR]', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_PROMOTION_EFFECT_WEAK_RANGED', 'attack vs [COLOR_NEGATIVE_TEXT]Ground and Ships[ENDCOLOR]', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_PROMOTION_EFFECT_WHEN_ADJACENT_FRIENDLY', 'when [COLOR_POSITIVE_TEXT]Adjacent[ENDCOLOR] to a friendly military unit', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_PROMOTION_EFFECT_WHEN_EMBARKED', 'when [COLOR_POSITIVE_TEXT]Embarked[ENDCOLOR]', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_PROMOTION_EFFECT_WHEN_FLANKING', 'when [COLOR_POSITIVE_TEXT]Flanking[ENDCOLOR]', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_PROMOTION_EFFECT_WITH_GREAT_GENERAL', 'with [COLOR_POSITIVE_TEXT]Great General[ENDCOLOR] in same tile', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_PROMOTION_EFFECT_WITHDRAW', 'chance to withdraw from melee attacks', '', '');
/* Promotion Names */
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_PROMOTION_ANTI_FIGHTER', 'Bonus vs Fighters (50)', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_PROMOTION_ANTI_HELICOPTER', 'Bonus vs Helicopters (100)', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_PROMOTION_ANTI_TANK', 'Bonus vs Tanks (100)', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_PROMOTION_ARCTIC_POWER', 'Arctic Power', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_PROMOTION_DEFENSE_PENALTY_50', 'Penalty on Defense (50)', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_PROMOTION_DEFENSE_PENALTY_50', 'Penalty on Defense (50)', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_PROMOTION_DESERT_POWER', 'Desert Power', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_PROMOTION_EMBARKED_DEFENSE', 'Embarked Defense (100)', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_PROMOTION_FOREIGN_LANDS', 'Foreign Lands Bonus (20)', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_PROMOTION_HANDICAP', 'AI Handicap', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_PROMOTION_HANDICAP_1', 'AI Handicap I', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_PROMOTION_HANDICAP_2', 'AI Handicap II', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_PROMOTION_HILL_FIGHTER', 'Hill Fighter', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_PROMOTION_MERCENARY', 'Mercenary', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_PROMOTION_MOUNTED_PENALTY', 'Penalty vs Mounted (50)', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_PROMOTION_NAVAL_PENALTY', 'Penalty Attacking Ships (50)', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_PROMOTION_NEW_UNIT', 'New Unit', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_PROMOTION_NEW_UNIT_HELP', 'New Unit', '', '');
INSERT INTO Cep_Language_EN_US (DateModified, Tag, Text, Gender, Plurality) VALUES (date('2013-01-18'), 'TXT_KEY_PROMOTION_WEAK_RANGED', 'Ground Attack Penalty (50)', '', '');



UPDATE LoadedFile SET Value=1 WHERE Type='Text_TW_PromotionStats.sql';
